project_name: levant

builds:
  -
    binary: levant
    env:
    - CGO_ENABLED=0

    # GOOS list to build in.
    # For more info refer to https://golang.org/doc/install/source#environment
    goos:
      - darwin
      - freebsd
      - linux

    # GOARCH to build in.
    # For more info refer to https://golang.org/doc/install/source#environment
    goarch:
      - amd64
      - i386
      - arm

    # List of combinations of GOOS + GOARCH + GOARM to ignore.
    # Default is empty.
    ignore:
      - goos: darwin
        goarch: arm

    # Custom ldflags template.
    # This is parsed with Golang template engine and the following variables
    # are available:
    # - Date
    # - Commit
    # - Tag
    # - Version (Tag with the `v` prefix stripped)
    # The default is `-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}`
    # Date format is `2006-01-02_15:04:05`
    ldflags: -s -w -X main.Name={{ .ProjectName }} -X main.Version={{.Version}} -X main.GitCommit={{.Commit}}"

archive:
  # You can change the name of the archive.
  # This is parsed with Golang template engine and the following variables
  # are available:
  # - ProjectName
  # - Tag
  # - Version (Tag with the `v` prefix stripped)
  # - Os
  # - Arch
  # - Arm (ARM version)
  # The default is `{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}`
  name_template: "{{ .Os }}-{{ .Arch }}-{{ .ProjectName }}"

  # Archive format. Valid options are `tar.gz`, `zip` and `binary`.
  # If format is `binary` no archives are created and the binaries are instead uploaded directly.
  # In that case name_template the below specified files are ignored.
  # Default is `tar.gz`
  format: binary

  # Additional files/globs you want to add to the archive.
  # Defaults are any files matching `LICENCE*`, `LICENSE*`,
  # `README*` and `CHANGELOG*` (case-insensitive)
  #files:
  #  - LICENSE
  #  - README.md
  #  - CHANGELOG.md

release:
  # Repo in which the release will be created.
  # Default is extracted from the origin remote URL.
  github:
    owner: jrasell
    name: levant